import type { Invitation } from './types';

export const demoInvitations: Invitation[] = [
  {
    id: '8a0f8b1e-67e8-4fa8-ae3e-291120260001',
    slug: 'tho-va-tham',
    status: 'published',
    partnerOne: 'Văn Thọ',
    partnerTwo: 'Hồng Thắm',
    partnerOneFullName: 'Nguyễn Văn Thọ',
    partnerTwoFullName: 'Trương Thị Hồng Thắm',
    partnerOneParents: 'Ông A · Bà B',
    partnerTwoParents: 'Ông C · Bà D',
    partnerOneAddress: 'Ba Đình, Hà Nội',
    partnerTwoAddress: 'Cầu Giấy, Hà Nội',
    headline: 'Trân trọng kính mời',
    message: 'Cùng gia đình, Văn Thọ và Hồng Thắm hân hạnh mời bạn đến chung vui trong ngày bắt đầu hành trình mới của chúng mình.',
    story: 'Giữa rất nhiều cuộc gặp gỡ, chúng mình đã tìm thấy một người để cùng đi qua những ngày bình thường đẹp nhất.',
    coverImage: '/photos/wedding-05.webp?v=20260923-2',
    coverAlt: 'Văn Thọ và Hồng Thắm trong bộ ảnh cưới',
    dressCode: 'Trang phục lịch sự - Bạn hãy cứ diện bộ đồ cảm thấy đẹp và tự tin nhất ♥',
    closingMessage: 'Sự hiện diện của bạn là món quà quý giá nhất đối với chúng mình.',
    rsvpEnabled: true,
    rsvpDeadline: '2026-11-23T23:59:00+07:00',
    wishesEnabled: true,
    giftsEnabled: true,
    events: [
      {
        id: 'demo-ceremony', title: 'Lễ thành hôn', dateTime: '2026-11-29T09:00:00+07:00',
        lunarDate: 'Tức ngày 21 tháng 10 năm Bính Ngọ', venue: 'Tư gia nhà gái',
        address: 'Cầu Giấy, Hà Nội', mapUrl: 'https://www.google.com/maps/search/?api=1&query=C%E1%BA%A7u+Gi%E1%BA%A5y+H%C3%A0+N%E1%BB%99i', sortOrder: 0,
      },
      {
        id: 'demo-reception', title: 'Tiệc cưới', dateTime: '2026-11-29T09:00:00+07:00',
        arrivalTime: '08:30', lunarDate: 'Tức ngày 21 tháng 10 năm Bính Ngọ', venue: 'Nhà Văn Hóa Thôn An Tử 2', address: 'Xã Tiên Lãng, Thành phố Hải Phòng',
        mapUrl: 'https://www.google.com/maps/dir/?api=1&destination=Nh%C3%A0+V%C4%83n+H%C3%B3a+Th%C3%B4n+An+T%E1%BB%AD+2%2C+X%C3%A3+Ti%C3%AAn+L%C3%A3ng%2C+Th%C3%A0nh+ph%E1%BB%91+H%E1%BA%A3i+Ph%C3%B2ng', sortOrder: 1,
      },
    ],
    timeline: [
      { id: 't1', time: '08:30', title: 'Đón khách', sortOrder: 0 },
      { id: 't2', time: '09:00', title: 'Khai tiệc', sortOrder: 1 },
      { id: 't3', time: '09:15', title: 'Rót rượu, cắt bánh', sortOrder: 2 },
      { id: 't4', time: '09:20', title: 'Phục vụ món chính', sortOrder: 3 },
      { id: 't5', time: '11:30', title: 'Kết thúc tiệc', sortOrder: 4 },
    ],
    media: [
      { id: 'm1', url: '/photos/wedding-01.webp?v=20260923-2', alt: 'Ảnh cưới của Văn Thọ và Hồng Thắm', sortOrder: 0 },
      { id: 'm2', url: '/photos/wedding-02.webp?v=20260923-2', alt: 'Khoảnh khắc bên nhau của cô dâu và chú rể', sortOrder: 1 },
      { id: 'm3', url: '/photos/wedding-03.webp?v=20260923-2', alt: 'Khoảnh khắc cưới của Văn Thọ và Hồng Thắm', sortOrder: 2 },
      { id: 'm4', url: '/photos/wedding-04.webp?v=20260923-2', alt: 'Chân dung cưới của Văn Thọ và Hồng Thắm', sortOrder: 3 },
      { id: 'm5', url: '/photos/wedding-06.webp?v=20260923-2', alt: 'Cô dâu và chú rể trong ngày chụp ảnh cưới', sortOrder: 4 },
      { id: 'm6', url: '/photos/wedding-07.webp?v=20260923-2', alt: 'Khoảnh khắc hạnh phúc của đôi uyên ương', sortOrder: 5 },
      { id: 'm7', url: '/photos/wedding-08.webp?v=20260923-2', alt: 'Ảnh cưới kỷ niệm của Văn Thọ và Hồng Thắm', sortOrder: 6 },
    ],
    gifts: [],
    wishes: [],
  },
  {
    id: 'demo-lan-huy',
    slug: 'lan-va-huy',
    status: 'published',
    partnerOne: 'Huy',
    partnerTwo: 'Lan',
    headline: 'Ngày vui của chúng mình',
    message: 'Một buổi chiều ấm áp sẽ trọn vẹn hơn khi có bạn ở bên. Hẹn gặp bạn trong ngày đặc biệt của Lan và Huy.',
    closingMessage: 'Cảm ơn bạn đã là một phần trong câu chuyện của chúng mình.',
    rsvpEnabled: false,
    wishesEnabled: false,
    giftsEnabled: true,
    events: [{ id: 'e2', title: 'Tiệc cưới', dateTime: '2027-03-14T18:00:00+07:00', venue: 'Không gian tiệc cưới', address: 'TP. Hồ Chí Minh', sortOrder: 0 }],
    timeline: [], media: [], gifts: [], wishes: [],
  },
];
