import type { Invitation } from './types';

export const demoInvitations: Invitation[] = [
  {
    id: 'demo-tho-tham',
    slug: 'tho-va-tham',
    status: 'published',
    partnerOne: 'Thọ',
    partnerTwo: 'Thắm',
    headline: 'Trân trọng kính mời',
    message: 'Cùng gia đình, Thọ và Thắm hân hạnh mời bạn đến chung vui trong ngày bắt đầu hành trình mới của chúng mình.',
    story: 'Giữa rất nhiều cuộc gặp gỡ, chúng mình đã tìm thấy một người để cùng đi qua những ngày bình thường đẹp nhất.',
    coverImage: '/photos/wedding-03.webp',
    coverAlt: 'Cặp đôi chụp ảnh cưới trong khu vườn',
    dressCode: 'Trang phục lịch sự · Ưu tiên kem, nâu và đỏ trầm',
    closingMessage: 'Sự hiện diện của bạn là món quà quý giá nhất đối với chúng mình.',
    rsvpEnabled: true,
    rsvpDeadline: '2027-01-17T23:59:00+07:00',
    wishesEnabled: true,
    giftsEnabled: false,
    events: [
      {
        id: 'demo-ceremony', title: 'Lễ thành hôn', dateTime: '2027-01-23T09:00:00+07:00',
        lunarDate: 'Ngày âm lịch sẽ được gia đình xác nhận', venue: 'Tư gia nhà gái',
        address: 'Hà Nội', sortOrder: 0,
      },
      {
        id: 'demo-reception', title: 'Tiệc cưới', dateTime: '2027-01-23T18:00:00+07:00',
        arrivalTime: '17:30', venue: 'Trung tâm tiệc cưới', address: 'Hà Nội', sortOrder: 1,
      },
    ],
    timeline: [
      { id: 't1', time: '17:30', title: 'Đón khách', sortOrder: 0 },
      { id: 't2', time: '18:00', title: 'Khai tiệc', sortOrder: 1 },
      { id: 't3', time: '18:30', title: 'Nghi thức thành hôn', sortOrder: 2 },
      { id: 't4', time: '19:00', title: 'Nâng ly chúc mừng', sortOrder: 3 },
    ],
    media: [
      { id: 'm1', url: '/photos/wedding-03.webp', alt: 'Cặp đôi trong khu vườn', sortOrder: 0 },
      { id: 'm2', url: '/photos/wedding-07.webp', alt: 'Cặp đôi trong khu vườn trắng', sortOrder: 1 },
      { id: 'm3', url: '/photos/wedding-10.webp', alt: 'Cặp đôi bên vườn hoa', sortOrder: 2 },
      { id: 'm4', url: '/photos/wedding-12.webp', alt: 'Cặp đôi dạo bước cùng nhau', sortOrder: 3 },
      { id: 'm5', url: '/photos/wedding-01.webp', alt: 'Khoảnh khắc trong studio', sortOrder: 4 },
      { id: 'm6', url: '/photos/wedding-05.webp', alt: 'Ảnh cưới studio với hoa', sortOrder: 5 },
    ],
    gifts: [],
    wishes: [],
  },
  {
    id: 'demo-lan-huy',
    slug: 'lan-va-huy',
    status: 'published',
    partnerOne: 'Huy',
    partnerTwo: 'Lan',
    headline: 'Ngày vui của chúng mình',
    message: 'Một buổi chiều ấm áp sẽ trọn vẹn hơn khi có bạn ở bên. Hẹn gặp bạn trong ngày đặc biệt của Lan và Huy.',
    closingMessage: 'Cảm ơn bạn đã là một phần trong câu chuyện của chúng mình.',
    rsvpEnabled: false,
    wishesEnabled: false,
    giftsEnabled: false,
    events: [{ id: 'e2', title: 'Tiệc cưới', dateTime: '2027-03-14T18:00:00+07:00', venue: 'Không gian tiệc cưới', address: 'TP. Hồ Chí Minh', sortOrder: 0 }],
    timeline: [], media: [], gifts: [], wishes: [],
  },
];
